spring:
  spring:
    datasource:
      primary:
        url: jdbc:postgresql://primary-host:5432/RetailDb
        username: user
        password: pass

      replicas:
        - url: jdbc:postgresql://replica1-host:5432/RetailDbReplic
          username: user
          password: pass
#        - url: jdbc:postgresql://replica2-host:5432/db // ????????? ?????????????? ???????
#          username: user
#          password: pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org.hibernate.SQL: WARN
      org.hibernate.type.descriptor.sql: WARN

